### ISSUE TITLE
 Question about  the runtime of the Schrieffer-Wolff (SW) package！

### ISSUE THREAD

**Issue by jsfeng-fudan** [dkweiss31/Schrieffer-Wolff#1]
I have a question regarding the runtime of the Schrieffer-Wolff (SW) package. When I follow the example provided by the author and run the SW package, the calculation gets stuck when computing the 4th-order perturbation and has been running for 3 days without producing a result. My computing platform is Windows 10 + Mathematica 12 + SNEG 2.0.3.

**Comment by dkweiss31** [comment]
Hi @jsfeng-fudan! So this package was just making public some code I wrote as part of my thesis, which you can find [here](https://bpb-us-e1.wpmucdn.com/sites.northwestern.edu/dist/2/1168/files/2022/08/Danny_Thesis_Final.pdf), see Appendix A. I'm not certain why the calculation is taking so long on your platform: redownloading the code and running the first example, the fourth order effective Hamiltonian is computed in a few seconds and the sixth-order effective Hamiltonian takes about a minute (the second example is similarly fast). I am using a more outdated version of SNEG 1.250, so I wonder if you try downgrading to that version.
